### ISSUE TITLE
iChunUtil-1.16.5-10.5.1.jar vs Better End Sky (Forge) EndSky-1.2.jar  Critical Error whilst initiating

### ISSUE THREAD

**Issue by GentlemanGnu** [iChun/iChunUtil#229] opened 2022-01-21 08:30 UTC
Was requested to add Hats and Googly Eyes to my latest modpack.   Upon doing so, I kept getting "Error, Game Crashed".  Snce there are 130 mods in my pack, I have narrowed it down for you.  I don't know which one is not playing nicely.

the essentials... 
Forge 1.16.5-36.2.22.jar
java  1.8.0_51, Oracle Corporation

Mod List: 
		iChunUtil-1.16.5-10.5.1.jar |10.5.1 
		EndSky-1.2.jar Better End Sky 1.2 
		
The game crashes whilst initiating.  Crash repeatable with just these 2 mods included.  I'm using the Curseforge Launcher, if that helps at all.

 full crash report available on request.
 
 Exerpt:

Time: 1/21/22 7:17 PM
Description: Initializing game

org.spongepowered.asm.mixin.transformer.throwables.MixinTransformerError: An unexpected critical error was encountered
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.applyMixins(MixinProcessor.java:392) ~[mixin-0.8.4.jar:0.8.4+Jenkins-b308.git-2accda5000f7602229606b39437565542cc6fba4] {}
	at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClass(MixinTransformer.java:250) ~[mixin-0.8.4.jar:0.8.4+Jenkins-b308.git-2accda5000f7602229606b39437565542cc6fba4] {}
	at org.spongepowered.asm.service.modlauncher.MixinTransformationHandler.processClass(MixinTransformationHandler.java:131) ~[mixin-0.8.4.jar:0.8.4+Jenkins-b308.git-2accda5000f7602229606b39437565542cc6fba4] {}

**Comment by iChun** [comment] 2022-01-21 09:29
I'm going to need the full log

**Comment by iChun** [comment] 2022-01-21 14:57
As we discussed privately on Discord, the issue is on the Better End Sky end. Closing.

**Closed as completed by iChun** 2022-01-21 14:57 UTC
