### ISSUE TITLE
Memory Leak on Renderer

### ISSUE THREAD

**Issue by notfood** [iChun/iChunUtil#177] opened 2018-08-24 00:37 UTC
There is a memory leak in the renderer whenever IChunUtil is installed.

Hit this issue with CustomNPC mod but it affects other mods as well. Grimoire of Gaia is another mod affected. The setup to reproduce is simple, just line the mods and wait. The more mobs, the more ram is leaked.

This issue happens under Windows and Linux, I couldn't test on Mac.

#### Enviroment used for test:
```ts
Linux 4.18.3 ArchLinux
Java 8.181

Minecraft 1.12.2
Forge 1.12.2-14.23.4.2756

iChunUtil 1.12.2-7.1.4
CustomNPCs 1.12.2 (09jul18)
```

##### Recorded for reference:
[![IMAGE ALT TEXT HERE](http://img.youtube.com/vi/iSeKi1VT1m0/0.jpg)](https://youtu.be/iSeKi1VT1m0)
There is no ram ramp up here, no matter how long you wait.

##### With iChunUtil added:
[![IMAGE ALT TEXT HERE](http://img.youtube.com/vi/kU_LXtOz3CM/0.jpg)](https://youtu.be/kU_LXtOz3CM)
There is a 20mb/s ramp up of ram usage here, eventually it runs out of memory and will crash to desktop. I speed it up so it's noticeable.

**Comment by thedeadman782004** [comment] 2018-12-14 19:21
Same issue.

**Comment by DemonfangArun** [comment] 2019-01-09 02:11
What precisely does it take to trigger this issue? I have had ichunutil and moreplayermodels installed in my pack for months and haven't experienced this memory issue (or at least not to the extent above). I've been able to play for hours on end with 8GB of ram allocated, and most of that is already in use from the get-go.

**Comment by thedeadman782004** [comment] 2019-01-09 16:06
The issue is triggered by having iChunUtil and Custom NPCs.  I haven't tried it with More Player Models.  Then to start the leak, you simply spawn in an NPC.

**Comment by talonos2** [comment] 2019-01-29 22:54
Can confirm. It's somehow leaking _outside_ of heap space, so you cannot protect yourself with -xmx command line parameters. I had 32 GB ram, and I went to lunch, and came back to find it had all filled up and spilled over into swap space.

**Comment by iChun** [comment] 2019-03-01 22:21
Good news, I've spoken to Noppes and he's identified the issue on his end. It should be fixed in his mods from the next release.

**Closed by iChun** 2019-03-01 22:21 UTC

**Comment by Celophy** [comment] 2019-09-16 14:08
help, i have the same problem!!

**Comment by thedeadman782004** [comment] 2019-09-16 14:22
If you read above you will see the comment by iChun that Noppes is fixing the problem. I’m not sure if that fix has been released yet or not.
